const a = 1;
console.log(a);
console.log(typeof a);
const b = 2;
console.log(b);
const c = a + b;
console.log(c);
const name = "JG";
console.log(name);
console.log(typeof name);
const role = "gamer";
console.log(name + role);
console.log(name + " " + role);
console.log(name, role);
